### ISSUE TITLE
Change FAB icon

### ISSUE THREAD

**Issue by AishwaryaSurana** [SiDevesh/React-Native-FAB#6]
Can i change the icon from "**+**" to any image icon of my choice. I dont want to use material icons What I tried is:

```

    <FAB
       buttonColor="#fca335"
       iconTextComponent={ 
           <Image
                  source={require('../img/right.png')}
                 style={styles.rightIconStyle}
            />
        }
        iconTextColor="#FFFFFF"
        onClickAction={() => {this.popupDialog.show();}}
        visible={true} />


```

**Comment by SiDevesh** [comment]
HI, this was built to be used with font icons like the ones in [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons). See if any in `react-native-vector-icons` fits your need. Otherwise, implementing images for icon shouldn't be much hard. Here's a relevant section in source https://github.com/SiDevesh/React-Native-FAB/blob/master/index.js#L189.
